import type { Metadata } from "next";
import "./globals.css";

import { Outfit } from "next/font/google";

import { WishlistProvider } from "@/app/context/WishlistContext1"; // Wishlist context import kiya
import ReduxProvider from "./redux/provider";



// Font Optimization: Using swap for better performance
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap", // Font display swap for better load performance
});

// Lazy Loading Navbar and Footer components


export const metadata: Metadata = {
  title: "Avion",
  description: "Generated by basit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <head>
        {/* Preload critical fonts for faster rendering */}
        <link
          rel="preload"
          href="/path/to/font-file.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body className={outfit.className}>
        <ReduxProvider>
          <WishlistProvider>
            
            {children}
            
          </WishlistProvider>
        </ReduxProvider>
      </body>
    </html>
   
  );
}
